# NLP4 - Text Processing Techniques: TF-IDF and LDA

In this session we will explore powerful techniques for understanding and analyzing text data. Two key concepts you'll learn are TF-IDF and LDA.

TF-IDF (Term Frequency-Inverse Document Frequency) is a method used to evaluate how important a word is in a document relative to a collection of documents. It helps filter out common words while highlighting those that are more meaningful in specific contexts.

LDA (Latent Dirichlet Allocation) is a topic modeling technique. It helps identify underlying topics in a set of documents by grouping words that frequently appear together.

These tools will give you insights into patterns in text data, opening doors to advanced text analysis!

---

## Install Libraries

In [ ]:
#first lets install datasets library
!pip install datasets
!python -m spacy download pt_core_news_lg

## Imports

In [2]:
#dataset library
from datasets import load_dataset
#load dataset
dataset = load_dataset("tclopess/sinopsys_movies_portuguese")
#convert it to pandas and slice the first 3000 data points
df_sinop = dataset['train'].to_pandas()[:3000]


#NLP tool box nltk
import nltk
from nltk.corpus import stopwords
#getting stop words
nltk.download('stopwords')
stop = list(set(stopwords.words('portuguese')))
print(stop)

#string library
import string
#get list of punctuations
pontuacoes = string.punctuation
print(pontuacoes)

#NLP toolbox spacy
import spacy
#load portuguese module large
nlp = spacy.load("pt_core_news_lg")

#other python support libraries and methods
import itertools
from collections import Counter
from collections import defaultdict
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

#dataframes library
import pandas as pd

#LDA library
import gensim
import gensim.corpora as corpora
from gensim.models.ldamodel import LdaModel

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/645 [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/3.50M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/625k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/17947 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3168 [00:00<?, ? examples/s]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

['eu', 'houvera', 'tem', 'elas', 'tivemos', 'esteja', 'fui', 'não', 'fossem', 'me', 'de', 'houverão', 'haver', 'havemos', 'temos', 'te', 'sua', 'terão', 'sejamos', 'seremos', 'ele', 'uma', 'estiveram', 'pelos', 'seu', 'meu', 'dele', 'estava', 'estivéssemos', 'tivera', 'esses', 'houveriam', 'lhes', 'você', 'tenha', 'nas', 'muito', 'qual', 'aqueles', 'está', 'minha', 'ela', 'hajam', 'hajamos', 'minhas', 'e', 'mesmo', 'também', 'fôssemos', 'num', 'lhe', 'numa', 'pelo', 'houvéssemos', 'forem', 'teremos', 'eles', 'fomos', 'houvesse', 'o', 'no', 'os', 'do', 'tenham', 'teríamos', 'terei', 'teu', 'terá', 'sejam', 'teriam', 'tiver', 'houverei', 'mais', 'houveríamos', 'seriam', 'estamos', 'às', 'estão', 'nosso', 'tua', 'delas', 'seria', 'estejamos', 'há', 'estiver', 'ao', 'houver', 'éramos', 'até', 'seja', 'dos', 'houverem', 'foram', 'estávamos', 'por', 'sou', 'hão', 'eram', 'fosse', 'vocês', 'essa', 'estou', 'esta', 'isto', 'aquele', 'um', 'nossos', 'houve', 'ou', 'tuas', 'formos', 'fora', 'fôramos', 'se', 'essas', 'tiverem', 'depois', 'estivessem', 'seus', 'esteve', 'ser', 'tive', 'as', 'estivéramos', 'tivéramos', 'houvéramos', 'como', 'quando', 'pela', 'teve', 'tinha', 'nós', 'das', 'foi', 'nossas', 'era', 'serei', 'for', 'dela', 'já', 'da', 'haja', 'à', 'deles', 'teus', 'tivesse', 'tivéssemos', 'tu', 'com', 'em', 'estive', 'estejam', 'hei', 'aquela', 'teria', 'a', 'seríamos', 'somos', 'nossa', 'tínhamos', 'estiverem', 'estavam', 'houvermos', 'será', 'tiveram', 'estivemos', 'tenho', 'nos', 'esse', 'entre', 'tém', 'vos', 'serão', 'houvemos', 'na', 'são', 'aos', 'houveram', 'nem', 'isso', 'houverá', 'estes', 'estivesse', 'quem', 'só', 'houveremos', 'aquilo', 'tinham', 'mas', 'estivera', 'tivermos', 'estivermos', 'tivessem', 'sem', 'estar', 'estas', 'que', 'houvessem', 'para', 'houveria', 'pelas', 'este', 'suas', 'aquelas', 'tenhamos', 'é', 'meus']
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

## Term Frequency - Inverse Document Frequency (TF-IDF)

The **TF-IDF** (Term Frequency - Inverse Document Frequency) model is an improvement over the Bag of Words. It not only takes into account the frequency of words in a document but also considers how important a word is in the entire corpus. The idea is that words that appear frequently in a document but rarely in the rest of the corpus are more meaningful for that document. TF-IDF assigns higher weights to such terms, thus reducing the impact of common words (e.g., "the", "and").

- **Term Frequency (TF)**: Measures how often a word appears in a document.
- **Inverse Document Frequency (IDF)**: Reduces the weight of commonly occurring words across multiple documents.

TF-IDF helps prioritize terms that are more informative for distinguishing between documents.

### Practicing

1 - Using the concepts from the previous class, create a function that takes a string as a parameter and returns a list of pre-processed tokens. The tokens should be lowercase, lemmas, and must not be punctuation or stopwords.

In [9]:
#funcao de preprocessing com lemmas
def preprocessing(text):
  return [x.lemma_.lower() for x in nlp(text) if x.text.lower() not in stop and x.text not in pontuacoes]

2 - Using the function you created in the previous exercise, preprocess all the synopsis texts contained in the dataframe.

In [10]:
preprocessed_docs = [preprocessing(x) for x in df_sinop['sinopse'].to_list()]

In [11]:
preprocessed_docs[0]

['história',
 'primeiro',
 'grande',
 'batalha',
 'fase',
 'americano',
 'guerra',
 'vietnã',
 'soldado',
 'ambos',
 'lado',
 'travar']

3 - Create a dataframe containing the tf values for all tokens in the documents. Consider the function below:

$$
TF(t,d) = \frac{\text{Number of times the term } t \text{ appears in the document } d } {\text{Total number of terms in the document } d}
$$

In [12]:
full_list = Counter(list(itertools.chain(*preprocessed_docs)))
print(full_list.most_common())

[('vida', 522), ('ano', 369), ('jovem', 342), ('descobrir', 337), ('dois', 319), ('encontrar', 310), ('enquanto', 294), ('amigo', 277), ('dever', 267), ('poder', 265), ('homem', 264), ('fazer', 260), ('história', 256), ('família', 251), ('pai', 243), ('tornar', 241), ('todo', 240), ('novo', 236), ('cidade', 235), ('começar', 231), ('casa', 213), ('mundo', 211), ('tentar', 207), ('sobre', 198), ('filme', 194), ('grande', 187), ('filho', 185), ('levar', 183), ('guerra', 177), ('onde', 177), ('outro', 174), ('contra', 171), ('matar', 162), ('mulher', 162), ('lutar', 160), ('conhecer', 157), ('durante', 154), ('após', 152), ('grupo', 150), ('ficar', 149), ('assassino', 143), ('amor', 136), ('vez', 132), ('...', 131), ('próprio', 131), ('assassinato', 127), ('dia', 126), ('ter', 126), ('morte', 124), ('chamar', 123), ('terra', 122), ('policial', 121), ('filha', 121), ('tempo', 121), ('tudo', 120), ('mãe', 120), ('adolescente', 119), ('ver', 119), ('irmão', 119), ('três', 118), ('misterioso', 117), ('americano', 116), ('agente', 116), ('apenas', 115), ('agora', 114), ('pessoa', 112), ('antes', 112), ('deixar', 111), ('envolver', 111), ('bom', 110), ('chegar', 109), ('decidir', 108), ('enfrentar', 108), ('salvar', 108), ('ir', 106), ('missão', 105), ('único', 101), ('logo', 100), ('ajudar', 100), ('viver', 99), ('passar', 98), ('apaixonar', 98), ('acabar', 97), ('esposo', 97), ('algum', 97), ('mudar', 97), ('busca', 96), ('nova', 95), ('trabalhar', 92), ('pequeno', 92), ('local', 92), ('coisa', 92), ('the', 91), ('equipe', 91), ('crime', 90), ('garota', 90), ('perder', 90), ('noite', 89), ('força', 88), ('menino', 87), ('seguir', 87), ('enviar', 87), ('primeiro', 86), ('volta', 86), ('série', 85), ('estranho', 83), ('forçar', 83), ('procurar', 83), ('velho', 83), ('usar', 82), ('caminho', 82), ('criminoso', 81), ('criança', 80), ('contar', 80), ('secreto', 80), ('york', 80), ('último', 80), ('dar', 79), ('dinheiro', 79), ('casal', 79), ('passado', 79), ('relacionamento', 78), ('escapar', 77), ('sequestrar', 77), ('roubar', 77), ('gangue', 76), ('caso', 76), ('cada', 75), ('criar', 74), ('conseguir', 74), ('transformar', 73), ('junto', 73), ('colocar', 73), ('trabalho', 71), ('meio', 71), ('ajuda', 70), ('voltar', 70), ('receber', 70), ('antigo', 70), ('jogo', 69), ('problema', 69), ('casamento', 69), ('aventura', 69), ('viajar', 68), ('ser', 68), ('humano', 68), ('cujo', 68), ('irmã', 67), ('futuro', 67), ('viagem', 67), ('entrar', 66), ('manter', 66), ('perseguir', 66), ('natal', 66), ('droga', 65), ('parecer', 65), ('prisão', 65), ('sair', 65), ('retornar', 65), ('investigar', 64), ('escola', 64), ('então', 64), ('mundial', 64), ('morrer', 63), ('longo', 62), ('polícia', 62), ('ainda', 62), ('ação', 62), ('detetive', 61), ('planejar', 61), ('mortal', 61), ('evento', 61), ('parte', 61), ('verdadeiro', 61), ('verdade', 61), ('querer', 61), ('soldado', 60), ('assassinar', 60), ('quatro', 60), ('romance', 60), ('juntar', 58), ('perceber', 58), ('vingança', 58), ('assumir', 57), ('próximo', 57), ('em este', 57), ('chefe', 57), ('segredo', 57), ('sobreviver', 57), ('final', 57), ('fugir', 56), ('colega', 56), ('plano', 56), ('sempre', 56), ('luta', 56), ('entanto', 56), ('mal', 55), ('contratar', 55), ('carro', 55), ('saber', 55), ('marido', 55), ('coração', 55), ('real', 54), ('estrela', 54), ('recuperar', 54), ('sonho', 54), ('inimigo', 54), ('namorada', 53), ('trazer', 53), ('país', 53), ('pouco', 53), ('medida', 53), ('destruir', 52), ('tomar', 52), ('corpo', 51), ('amizade', 51), ('perigoso', 51), ('sucesso', 51), ('ilha', 51), ('militar', 50), ('forma', 50), ('rico', 50), ('ganhar', 50), ('rua', 50), ('unir', 50), ('batalha', 49), ('século', 49), ('poderoso', 49), ('sob', 49), ('britânico', 49), ('john', 49), ('acidente', 49), ('embarcar', 48), ('ameaçar', 48), ('arma', 47), ('década', 47), ('aprender', 47), ('acontecer', 47), ('ladrão', 47), ('cientista', 47), ('revelar', 47), ('bandido', 47), ('precisar', 47), ('trás', 46), ('pegar', 46), ('muito', 45), ('terror', 45), ('esperar', 45), ('unidos', 45), ('namorado', 45), ('médio', 45), ('maneira', 44), ('exército', 44), ('destino', 44), ('belo', 44), ('proteger', 44), ('lugar', 44), ('planeta', 44), ('estados', 44), ('campo', 44), ('eua', 44), ('governo', 44), ('liderar', 44), ('jornada', 43), ('prender', 43), ('incluir', 43), ('cinco', 43), ('buscar', 43), ('deserto', 43), ('alienígena', 43), ('jack', 43), ('lado', 42), ('tentativa', 42), ('desaparecer', 42), ('alto', 42), ('leia', 42), ('vários', 42), ('atrás', 42), ('esconder', 42), ('negócio', 41), ('professor', 41), ('conto', 41), ('comédia', 41), ('londres', 41), ('ataque', 41), ('nunca', 41), ('dentro', 40), ('difícil', 40), ('fim', 40), ('nenhum', 40), ('estudante', 40), ('cara', 40), ('morar', 40), ('vivo', 40), ('arte', 40), ('oficial', 40), ('esperança', 40), ('lendário', 39), ('vítima', 39), ('piloto', 39), ('emprego', 39), ('implacável', 39), ('herói', 38), ('resgatar', 38), ('algo', 38), ('líder', 38), ('libertar', 38), ('nada', 38), ('famoso', 38), ('infância', 37), ('mágico', 37), ('cheio', 37), ('los', 37), ('angeles', 37), ('quase', 37), ('controle', 36), ('capturar', 36), ('rei', 36), ('acreditar', 36), ('nome', 36), ('ensino', 36), ('finalmente', 36), ('qualquer', 36), ('aluno', 35), ('especial', 35), ('diretor', 35), ('corrupto', 35), ('realmente', 35), ('médico', 35), ('reunir', 35), ('américa', 35), ('dr.', 35), ('vir', 35), ('michael', 35), ('lidar', 35), ('identidade', 35), ('sangue', 35), ('impedir', 35), ('traficante', 34), ('terrorista', 34), ('pesadelo', 34), ('sombrio', 34), ('amante', 34), ('estrada', 34), ('personagem', 34), ('james', 34), ('sozinho', 34), ('memória', 34), ('apresentar', 34), ('violento', 34), ('baseado', 34), ('sobrevivente', 34), ('treinar', 34), ('errar', 33), ('jogar', 33), ('acidentalmente', 33), ('corrida', 33), ('pessoal', 33), ('baixo', 33), ('caçador', 33), ('criatura', 33), ('guerreiro', 33), ('medo', 33), ('veterano', 33), ('atrair', 33), ('partir', 33), ('lei', 33), ('segunda', 33), ('morto', 33), ('vingar', 33), ('preso', 33), ('parceiro', 32), ('carreira', 32), ('preparar', 32), ('semana', 32), ('embora', 32), ('distante', 32), ('selvagem', 32), ('lá', 32), ('aceitar', 32), ('hora', 32), ('através', 32), ('pedir', 32), ('abandonar', 32), ('assim', 31), ('verão', 31), ('desde', 31), ('atacar', 31), ('negro', 31), ('chance', 31), ('serviço', 31), ('basear', 31), ('correr', 31), ('abrir', 31), ('diferente', 31), ('político', 31), ('tripulação', 31), ('remoto', 31), ('capitão', 31), ('acusar', 30), ('cinema', 30), ('advogado', 30), ('visitar', 30), ('dizer', 30), ('membro', 30), ('desenvolver', 30), ('fbi', 30), ('casar', 30), ('mistério', 30), ('floresta', 30), ('terrível', 30), ('encontro', 30), ('empresa', 30), ('programa', 30), ('humanidade', 30), ('solitário', 30), ('marcial', 30), ('zumbi', 29), ('lançar', 29), ('perfeito', 29), ('continuar', 29), ('gângster', 29), ('rock', 29), ('tom', 29), ('companheiro', 29), ('show', 29), ('mesmo', 29), ('dirigir', 29), ('david', 29), ('banco', 29), ('amar', 29), ('realidade', 29), ('início', 29), ('cair', 29), ('olhar', 29), ('segurança', 28), ('presidente', 28), ('música', 28), ('empresário', 28), ('internacional', 28), ('vampiro', 28), ('resgate', 28), ('conspiração', 28), ('aparentemente', 28), ('realizar', 28), ('evitar', 28), ('bem', 28), ('mestre', 28), ('resolver', 28), ('improvável', 27), ('norte', 27), ('classe', 27), ('caçar', 27), ('cabeça', 27), ('paris', 27), ('tornar se', 27), ('aterrorizar', 27), ('ameaça', 27), ('frank', 27), ('oferecer', 27), ('sexual', 27), ('desconhecer', 27), ('alvo', 27), ('killer', 27), ('cometer', 27), ('cuidar', 27), ('sul', 27), ('máfia', 27), ('garoto', 27), ('espírito', 27), ('califórnia', 27), ('ator', 26), ('férias', 26), ('documentário', 26), ('experiência', 26), ('iniciar', 26), ('organização', 26), ('fuga', 26), ('mau', 26), ('gato', 26), ('social', 26), ('tão', 26), ('comum', 26), ('sistema', 26), ('confrontar', 26), ('gêmeo', 26), ('papel', 26), ('amiga', 26), ('particular', 26), ('mão', 26), ('presente', 26), ('menina', 26), ('sam', 26), ('faculdade', 25), ('causar', 25), ('espacial', 25), ('derrubar', 25), ('festa', 25), ('príncipe', 25), ('cia', 25), ('reino', 25), ('rastrear', 25), ('interpretar', 25), ('serial', 25), ('parar', 25), ('mar', 25), ('formar', 25), ('bando', 25), ('rainha', 25), ('solteiro', 25), ('prestes', 25), ('escolher', 25), ('rival', 24), ('suspeito', 24), ('clássico', 24), ('separar', 24), ('importante', 24), ('decisão', 24), ('provar', 24), ('pagar', 24), ('inesperado', 24), ('malvado', 24), ('novamente', 24), ('determinar', 24), ('risco', 24), ('sociedade', 24), ('amoroso', 24), ('popular', 24), ('ouro', 24), ('time', 24), ('sete', 24), ('george', 24), ('trama', 24), ('se', 24), ('perigo', 24), ('artista', 24), ('adulto', 24), ('quarto', 23), ('espaço', 23), ('bebê', 23), ('recusar', 23), ('roubo', 23), ('terminar', 23), ('recrutar', 23), ('notório', 23), ('livro', 23), ('fronteira', 23), ('apartamento', 23), ('habilidade', 23), ('estilo', 23), ('elite', 23), ('acordar', 23), ('épico', 23), ('assalto', 23), ('defender', 23), ('paz', 23), ('richard', 23), ('sr.', 23), ('concordar', 23), ('jason', 23), ('superar', 23), ('hollywood', 23), ('sofrer', 23), ('monstro', 23), ('casado', 23), ('noiva', 23), ('motorista', 23), ('romântico', 23), ('feliz', 23), ('rápido', 23), ('peter', 23), ('violência', 23), ('civil', 23), ('navio', 23), ('seguro', 23), ('resto', 23), ('aparecer', 23), ('jornalista', 23), ('excêntrico', 22), ('convencer', 22), ('versão', 22), ('cumprir', 22), ('lua', 22), ('disfarçar', 22), ('geração', 22), ('descobrer', 22), ('primeira', 22), ('mike', 22), ('rapidamente', 22), ('desencadear', 22), ('derrotar', 22), ('momento', 22), ('visão', 22), ('atingir', 22), ('brilhante', 22), ('vizinho', 22), ('oeste', 22), ('princesa', 22), ('compartilhar', 22), ('louco', 22), ('pois', 22), ('russo', 21), ('entregar', 21), ('hospital', 21), ('mercenário', 21), ('deparar', 21), ('branco', 21), ('obter', 21), ('doença', 21), ('inspirar', 21), ('consequência', 21), ('thriller', 21), ('seis', 21), ('china', 21), ('maligno', 21), ('desejo', 21), ('vencer', 21), ('isolar', 21), ('recentemente', 21), ('construir', 21), ('bruxa', 21), ('fantasia', 21), ('tarde', 21), ('centrar', 21), ('tecnologia', 21), ('garantir', 21), ('testemunha', 21), ('responsável', 21), ('sequência', 21), ('fazendeiro', 21), ('destruição', 21), ('aspirante', 21), ('xerife', 20), ('mexicano', 20), ('refém', 20), ('deus', 20), ('quanto', 20), ('sobrenatural', 20), ('comprar', 20), ('conta', 20), ('loja', 20), ('participar', 20), ('drama', 20), ('animal', 20), ('tv', 20), ('general', 20), ('unidade', 20), ('fechar', 20), ('jim', 20), ('olho', 20), ('jogador', 20), ('condenar', 20), ('esforço', 20), ('banda', 20), ('jones', 20), ('milhão', 20), ('familiar', 20), ('segundo', 20), ('fantasma', 20), ('nave', 20), ('inocente', 20), ('escritor', 20), ('inglaterra', 20), ('avião', 20), ('caos', 20), ('fazenda', 20), ('ambos', 19), ('justiça', 19), ('desafio', 19), ('prisioneiro', 19), ('interior', 19), ('lenda', 19), ('fada', 19), ('estado', 19), ('horrível', 19), ('tio', 19), ("'s", 19), ('universitário', 19), ('dono', 19), ('universo', 19), ('várias', 19), ('armar', 19), ('guarda', 19), ('harry', 19), ('centro', 19), ('afetar', 19), ('repórter', 19), ('musical', 19), ('entrevista', 19), ('falar', 19), ('par', 19), ('aproximar', 19), ('crescer', 19), ('músico', 19), ('charles', 19), ('alguém', 19), ('público', 19), ('mostrar', 19), ('nazista', 19), ('ascensão', 19), ('projeto', 18), ('ninguém', 18), ('paciente', 18), ('principal', 18), ('funcionário', 18), ('max', 18), ('experimento', 18), ('nascer', 18), ('brutal', 18), ('lindo', 18), ('anterior', 18), ('sinistro', 18), ('competir', 18), ('aumentar', 18), ('inteligência', 18), ('estrelar', 18), ('operação', 18), ('transportar', 18), ('queda', 18), ('erro', 18), ('ato', 18), ('vilão', 18), ('liberdade', 18), ('escrever', 18), ('clube', 18), ('de esse', 18), ('conquistar', 18), ('emocionante', 18), ('nuclear', 18), ('caber', 18), ('frança', 18), ('invasão', 18), ('senhor', 18), ('convidar', 18), ('nick', 18), ('invadir', 18), ('lee', 18), ('vietnã', 17), ('pensar', 17), ('of', 17), ('bizarro', 17), ('totalmente', 17), ('hotel', 17), ('sobrevivência', 17), ('caça', 17), ('alice', 17), ('redor', 17), ('obscuro', 17), ('favorito', 17), ('designar', 17), ('visita', 17), ('oito', 17), ('desesperar', 17), ('robert', 17), ('descoberta', 17), ('computador', 17), ('área', 17), ('questão', 17), ('imaginar', 17), ('rebelde', 17), ('vila', 17), ('autoridade', 17), ('desafiar', 17), ('cruel', 17), ('adotar', 17), ('situação', 17), ('fugitivo', 17), ('traição', 17), ('administrar', 17), ('ex-presidiário', 17), ('longe', 17), ('tragédia', 17), ('profissional', 17), ('francês', 17), ('las', 17), ('talentoso', 17), ('noel', 17), ('paixão', 17), ('méxico', 17), ('porque', 17), ('trabalhador', 17), ('adotivo', 17), ('bob', 17), ('moderno', 17), ('povo', 17), ('tirar', 17), ('vínculo', 17), ('mudança', 17), ('desaparecimento', 17), ('acampamento', 17), ('controlar', 17), ('extraordinário', 17), ('permanecer', 17), ('gostar', 17), ('sentir', 16), ('enganar', 16), ('crise', 16), ('comunidade', 16), ('testemunhar', 16), ('vigilante', 16), ('submundo', 16), ('complexo', 16), ('repente', 16), ('mansão', 16), ('devido', 16), ('normal', 16), ('pista', 16), ('pobre', 16), ('máquina', 16), ('selva', 16), ('mês', 16), ('inocência', 16), ('montanha', 16), ('magnata', 16), ('causa', 16), ('quebrar', 16), ('sorte', 16), ('problemático', 16), ('prostituta', 16), ('forte', 16), ('marcar', 16), ('cruzar', 16), ('veer', 16), ('kevin', 16), ('bairro', 16), ('papai', 16), ('passeio', 16), ('fred', 16), ('cena', 16), ('frustrar', 16), ('paul', 16), ('futebol', 16), ('desonesto', 16), ('aéreo', 16), ('sexo', 16), ('vender', 16), ('super-herói', 16), ('féria', 16), ('dragão', 16), ('perspectiva', 16), ('surgir', 16), ('talento', 16), ('tarefa', 16), ('demônio', 16), ('propriedade', 16), ('conselho', 16), ('ordem', 16), ('estação', 15), ('rádio', 15), ('francisco', 15), ('danny', 15), ('torno', 15), ('pós-apocalíptico', 15), ('presa', 15), ('morador', 15), ('palavra', 15), ('texas', 15), ('vigarista', 15), ('duplo', 15), ('rumo', 15), ('torneio', 15), ('si', 15), ('12', 15), ('cachorro', 15), ('linha', 15), ('inglês', 15), ('filmar', 15), ('mergulhar', 15), ('limite', 15), ('mentor', 15), ('agência', 15), ('científico', 15), ('movimento', 15), ('perda', 15), ('heroína', 15), ('joe', 15), ('vegas', 15), ('exigir', 15), ('2', 15), ('cantor', 15), ('eliminar', 15), ('cantora', 15), ('atual', 15), ('bonito', 15), ('mafioso', 15), ('possível', 15), ('evidência', 15), ('japonês', 15), ('voar', 15), ('existir', 15), ('aposentado', 15), ('inferno', 15), ('mente', 15), ('suspeitar', 15), ('pacífico', 15), ('acompanhar', 15), ('intenção', 15), ('demais', 15), ('navegar', 15), ('decadente', 15), ('billy', 15), ('van', 15), ('vírus', 14), ('suicídio', 14), ('astuto', 14), ('personalidade', 14), ('dedicar', 14), ('viúva', 14), ('horror', 14), ('inesperadamente', 14), ('sarah', 14), ('recompensa', 14), ('cão', 14), ('comando', 14), ('gigante', 14), ('lutador', 14), ('atormentar', 14), ('steve', 14), ('além', 14), ('alex', 14), ('prova', 14), ('scott', 14), ('biológico', 14), ('austrália', 14), ('animar', 14), ('europa', 14), ('vontade', 14), ('academia', 14), ('esposa', 14), ('atividade', 14), ('processo', 14), ('investigação', 14), ('raça', 14), ('desajustar', 14), ('índia', 14), ('oportunidade', 14), ('cultura', 14), ('treinamento', 14), ('resposta', 14), ('itália', 14), ('1980', 14), ('alma', 14), ('felicidade', 14), ('jimmy', 14), ('considerar', 14), ('arthur', 14), ('inteligente', 14), ('comportamento', 14), ('tesouro', 14), ('claro', 14), ('teste', 14), ('complicado', 14), ('atrapalhar', 14), ('chicago', 14), ('especialista', 14), ('modelo', 14), ('base', 14), ('perto', 14), ('testar', 14), ('resultado', 14), ('terceiro', 14), ('trágico', 14), ('beira', 14), ('bordo', 14), ('existência', 14), ('direito', 14), ('baile', 14), ('vencedor', 14), ('carregar', 14), ('elizabeth', 14), ('20', 14), ('figura', 14), ('aterrorizante', 14), ('ferir', 13), ('cego', 13), ('apesar', 13), ('informar', 13), ('impiedoso', 13), ('sádico', 13), ('lista', 13), ('profundo', 13), ('desmoronar', 13), ('data', 13), ('amado', 13), ('uner', 13), ('idade', 13), ('charlie', 13), ('feminino', 13), ('televisão', 13), ('exatamente', 13), ('jackson', 13), ('conectar', 13), ('produtor', 13), ('desejar', 13), ('órfão', 13), ('city', 13), ('irlandês', 13), ('combinar', 13), ('dez', 13), ('conexão', 13), ('involuntariamente', 13), ('espião', 13), ('trair', 13), ('assombrar', 13), ('ensinar', 13), ('ambicioso', 13), ('árvore', 13), ('áfrica', 13), ('original', 13), ('tenente', 13), ('secretamente', 13), ('achar', 13), ('certo', 13), ('carta', 13), ('ideia', 13), ('indiano', 13), ('trocar', 13), ('enorme', 13), ('arriscar', 13), ('emoção', 13), ('gênio', 13), ('jay', 13), ('espalhar', 13), ('determinado', 13), ('johnson', 13), ('incomum', 13), ('italiano', 13), ('encarregar', 13), ('bar', 13), ('relação', 13), ('noivo', 13), ('campeão', 13), ('17', 13), ('garra', 13), ('vídeo', 13), ('desistir', 13), ('dificuldade', 13), ('assistente', 13), ('criação', 13), ('proteção', 13), ('beisebol', 13), ('diversão', 13), ('10', 13), ('kelly', 13), ('fotógrafo', 13), ('origem', 13), ('completar', 13), ('companhia', 13), ('sobrinho', 13), ('batman', 12), ('aliado', 12), ('vinte', 12), ('jane', 12), ('fonte', 12), ('tanto', 12), ('expedição', 12), ('habitante', 12), ('manhattan', 12), ('vira', 12), ('efeito', 12), ('infiltrar', 12), ('lembrar', 12), ('psiquiatra', 12), ('coleção', 12), ('tubarão', 12), ('experimentar', 12), ('perturbador', 12), ('tensão', 12), ('misteriosamente', 12), ('dor', 12), ('pronto', 12), ('vermelho', 12), ('lobo', 12), ('perturbar', 12), ('sequestro', 12), ('nacional', 12), ('ilegal', 12), ('aldeia', 12), ('bond', 12), ('expor', 12), ('ficção', 12), ('avançar', 12), ('ocorrer', 12), ('naval', 12), ('bill', 12), ('mídia', 12), ('henry', 12), ('mulherengo', 12), ('experiente', 12), ('arrastar', 12), ('indústria', 12), ('estabelecer', 12), ('dívida', 12), ('19', 12), ('lentamente', 12), ('conflito', 12), ('afeganistão', 12), ('afirmar', 12), ('confronto', 12), ('longa-metragem', 12), ('desesperadamente', 12), ('mutante', 12), ('sentimento', 12), ('pesquisa', 12), ('peça', 12), ('desaparecido', 12), ('rivalidade', 12), ('ford', 12), ('ingênuo', 12), ('esquema', 12), ('situado', 12), ('obcecado', 12), ('completo', 12), ('tratar', 12), ('época', 12), ('oscar', 12), ('fortuna', 12), ('lar', 12), ('narrar', 12), ('virar', 12), ('dominar', 12), ('moda', 12), ('sangrento', 12), ('soviético', 12), ('prédio', 12), ('oposto', 12), ('fama', 12), ('diamante', 12), ('dinossauro', 12), ('submarino', 12), ('relato', 11), ('superman', 11), ('restaurante', 11), ('examinar', 11), ('11', 11), ('pousar', 11), ('voz', 11), ('chegada', 11), ('sozinha', 11), ('dupla', 11), ('hilário', 11), ('turma', 11), ('ler', 11), ('permitir', 11), ('18', 11), ('ponto', 11), ('alemão', 11), ('adaptação', 11), ('produzir', 11), ('fé', 11), ('cineasta', 11), ('conjunto', 11), ('rato', 11), ('auge', 11), ('imigrante', 11), ('eventualmente', 11), ('apaixonado', 11), ('relutantemente', 11), ('seguinte', 11), ('de isso', 11), ('high', 11), ('duro', 11), ('motivo', 11), ('daniel', 11), ('chris', 11), ('aérea', 11), ('animação', 11), ('inteiro', 11), ('julgamento', 11), ('explora', 11), ('posse', 11), ('contato', 11), ('legado', 11), ('má', 11), ('ambientar', 11), ('véspera', 11), ('sargento', 11), ('andy', 11), ('atriz', 11), ('centena', 11), ('natureza', 11), ('30', 11), ('14', 11), ('informação', 11), ('videogame', 11), ('quadrilha', 11), ('divorciar', 11), ('ouvir', 11), ('caminhão', 11), ('cenário', 11), ('aniversário', 11), ('menos', 11), ('devastar', 

In [13]:
list_dict_tfs = []

for doc in preprocessed_docs:
  dict_doc = defaultdict(int)
  total_doc = len(doc)
  cont_doc = Counter(doc)
  for word in full_list:
    if word in cont_doc.keys():
        #faz uma soma
        dict_doc[word] = cont_doc[word]/total_doc
    else:
        dict_doc[word] = 0

  list_dict_tfs.append(dict_doc)

In [14]:
df_tf = pd.DataFrame(list_dict_tfs)

In [16]:
df_tf

,história,primeiro,grande,batalha,fase,americano,guerra,vietnã,soldado,ambos,...,finding,neverland,pan,j.m.,barrie,sylvia,wilder,lemmon,matthau,esgotado
0,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2996,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2997,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2998,0.028571,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.028571,0.057143,0.057143,0.028571,0.057143,0.028571,0.000000,0.000000,0.000000,0.000000
2999,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.034483,0.034483,0.034483,0.034483

4 - Now consider the IDF formula below. Calculate an IDF vector for all tokens in the corpus.

$$
IDF(t) = \log \left( \frac{\text{Number of documents in the corpus}}{\text{Number of documents where the term } t \text{ appears}} \right)
$$

In [24]:
#total of documents where t appears
#df(t) = occurrence of t in documents¶
# aqui desconsidero se o termo aparece mais de uma vez no mesmo documento
dic_dt = defaultdict(int)
for document in preprocessed_docs:
    #aqui retira os termos repetidos
    for token in set(document):
        dic_dt[token]+=1

# dic_dt

In [25]:
dic_dt['história']

232

In [26]:
#calcula o idf para cada termo
# o idf é um calculo do termo em relaçao ao set de documentos

import math

dic_idf = {}
for key in dic_dt:
    dic_idf[key]=math.log(len(preprocessed_docs)/((dic_dt[key])))


dic_idf['história']

2.559630195983937

5 - Analyze the TF and IDF separately. What would be their relationship with the corpus, with a specific document, or with a specific term?

In [27]:
#TF measures how often a term appears in a document relative to the total number of terms in that document. It indicates the importance of a term within that specific document.
#IDF assesses the importance of a term across the entire corpus (a collection of documents). It measures how unique or rare a term is. A term that appears in many documents will have a lower IDF score, while a term that appears in few documents will have a higher IDF score.

6 - Using the data structures you used to separately calculate the TF and IDF above, return the TF-IDF value for the token 'história' in document 45.

In [28]:
#tfs do termo para os documentos que ele aparece
token = 'história'
print(df_tf.loc[45,token]*dic_idf['história'])

0.15997688724899606

## Consine Similarity

In the BOW model, texts are represented as vectors that count the occurrence of words in each document, ignoring word order and focusing on frequency. The similarity between documents can be assessed using these vectors through metrics like **cosine similarity**. Cosine similarity measures the angle between two vectors, determining how similar the documents are based on the words they share, even if in different quantities. This allows for efficient comparison of text content using the vector representations created by BOW.

### Practicing

1 - Consider the vectors below. Which ones are most similar to each other?

In [ ]:
X = [0, 0, 0, 1, 1, 1]
Y = [1, 0, 0, 1, 1, 0]
Z = [0, 1, 0, 0, 0, 0]

2 - Answer the question above using the `cosine_similarity` function.

In [ ]:
X = np.array([0, 0, 0, 1, 1, 1]).reshape(1, 6)
Y = np.array([1, 0, 0, 1, 1, 0]).reshape(1, 6)
Z = np.array([0, 1, 0, 0, 0, 0]).reshape(1, 6)
print('X e Y', cosine_similarity(X, Y))
print('X e Z', cosine_similarity(X, Z))
print('Y e Z', cosine_similarity(Y, Z))

X e Y [[0.66666667]]
X e Z [[0.]]
Y e Z [[0.]]

2 -  Create a dataframe for the analyzed corpus, where each row represents a document and each column represents the unique tokens. Each row will therefore indicate how many times a particular token appears in a given document.

In [ ]:
#lista para criar um dataframe com os vetores BoW
list_dict_documents = []

#para cada documento
for document in preprocessed_docs:
    #cria-se um dicionado default
    cont_doc = Counter(document)
    dict_doc = defaultdict(int)
    for key in full_list.keys():
        if key in cont_doc.keys():
            #faz uma soma
            dict_doc[key] = cont_doc[key]
        else:
            dict_doc[key] = 0

    #adiciona ao final do looping a linha referente ao documento
    list_dict_documents.append(dict_doc)

In [ ]:
#criando o dataframe
df_cont = pd.DataFrame(list_dict_documents)
df_cont

,história,primeiro,grande,batalha,fase,americano,guerra,vietnã,soldado,ambos,...,finding,neverland,pan,j.m.,barrie,sylvia,wilder,lemmon,matthau,esgotado
0,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2998,1,0,0,0,0,0,0,0,0,0,...,1,2,2,1,2,1,0,0,0,0
2999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,1

3 - Consider the synopses below. Which of the 3 are most similar or discuss the same topic?

In [ ]:
df_sinop.loc[636,'sinopse']

'Quando a família de Frank Castle é assassinada por criminosos, ele trava uma guerra contra o crime como um assassino vigilante conhecido apenas como O Justiceiro.'

In [ ]:
df_sinop.loc[999,'sinopse']

'O mafioso e assassino de aluguel Jimmy Conlon tem uma noite para descobrir onde está sua lealdade: com seu filho distante, Mike, cuja vida está em perigo, ou seu melhor amigo de longa data, o chefe da máfia Shawn Maguire, que quer que Mike pague pela morte de seu próprio filho.'

In [ ]:
df_sinop.loc[14,'sinopse']

'Em julho de 1969, a corrida espacial terminou quando a Apollo 11 cumpriu o desafio do presidente Kennedy de “pousar um homem na Lua e trazê-lo de volta são e salvo à Terra”. Ninguém que testemunhou o pouso lunar jamais o esquecerá. O documentário de Al Reinert, For All Mankind, é a história dos vinte e quatro homens que viajaram para a lua, contada em suas palavras, em suas vozes, usando as imagens de suas experiências. Quarenta anos após o primeiro pouso na lua, continua sendo a obra de cinema mais radical e visualmente deslumbrante já feita sobre esse evento de abalar a terra.'

4 - Use the cosine similarity function to justify your answer.

In [ ]:
X = np.array(df_cont.loc[636]).reshape(1,12615)
Y = np.array(df_cont.loc[999]).reshape(1,12615)
# X = [[0, 0, 0], [1, 1, 1]]
# Y = [[1, 0, 0], [1, 1, 0]]
cosine_similarity(X, Y)

array([[0.04652421]])

In [ ]:
X = np.array(df_cont.loc[636]).reshape(1,12615)
Y = np.array(df_cont.loc[14]).reshape(1,12615)
# X = [[0, 0, 0], [1, 1, 1]]
# Y = [[1, 0, 0], [1, 1, 0]]
cosine_similarity(X, Y)

array([[0.]])

In [ ]:
X = np.array(df_cont.loc[999]).reshape(1,12615)
Y = np.array(df_cont.loc[14]).reshape(1,12615)
# X = [[0, 0, 0], [1, 1, 1]]
# Y = [[1, 0, 0], [1, 1, 0]]
cosine_similarity(X, Y)

array([[0.]])

## Topic Modelling and LDA

While TF-IDF is effective for identifying key terms, it doesn’t provide insight into the underlying topics within the text.

This is where **Topic Modeling** comes in. It’s a technique used to automatically uncover hidden topics in large collections of text. A widely-used topic modeling method is **Latent Dirichlet Allocation (LDA)**, which goes beyond word frequencies to model the distribution of topics across documents and the distribution of words within topics. LDA assumes that each document consists of multiple topics, and each topic consists of related words.

### Practicing

1 - Discuss the paper that originated LDA. Take notes below in order to understand what the model is and how a single document can be composed of multiple topics.

2 - For this study, we will use the `Gensim` library. The first step is to create a dictionary. Use `corpora.Dictionary()` to create a dictionary that we will use in the model. Understand what this dictionary is. Did we use the same preprocessing that we did for TF-IDF?

In [ ]:
# Create Dictionary
id2word = corpora.Dictionary(preprocessed_docs)

In [ ]:
id2word[0]

'ambos'

3 - As a second input, it is necessary to create the corpus for the `LdaModel()` function. Read the documentation and create a compatible corpus based on the preprocessing you have already done.

In [ ]:
# Term Document Frequency
corpus = [id2word.doc2bow(text) for text in preprocessed_docs]

In [ ]:
corpus[0]

[(0, 1),
 (1, 1),
 (2, 1),
 (3, 1),
 (4, 1),
 (5, 1),
 (6, 1),
 (7, 1),
 (8, 1),
 (9, 1),
 (10, 1),
 (11, 1)]

4 - One of the most important steps for topic modeling algorithms is determining how many topics to use as input. Discuss how this decision should be made. For testing, use `num_topics=10`.

In [ ]:
# Set number of topics
num_topics = 10

5 - Finally, create a model from the objects created so far using the function `LdaModel()`

In [ ]:
# Build LDA model
lda_model = LdaModel(
    corpus=corpus,
    id2word=id2word,
    num_topics=num_topics,
    passes=20,
    random_state=100
    )

6 - Explain and discuss what the parameters `random_state` and `passes` refer to.

In [ ]:
# random_state: This is comparable to 'seed' in many packages and libraries. LDA is probabilistic, not deterministic. This means that, even were we to train models with the same parameters on the same corpus, our models might vary minutely each time. random_state helps mitigate this variation and thereby aid reproducibility.
# passes: The number of times the algorithm passes through the whole corpus. This is comparable to 'epochs' in other packages and libraries.

7 - LDA provides two main outputs, the loadings and the scores. What do they refer to?

In [ ]:
# Loadings: These refer to the weights or coefficients that indicate how much each word contributes to the topic.
# Scores: Represent the transformed values of the data in terms of the new axes and are used to classify the observations into different groups or classes.

8 - Use `lda_model.print_topics()` to access the tokens that contribute to each of the created topics (Loadings).

In [ ]:
# Print the keywords for each topic
#Researchers use both qualitative and quantitative methods to evaluate models
lda_model.print_topics(num_words=20)

#Topics are words with highest probability in topic and the numbers are the probabilities of words appearing in topic distribution.

[(0,
  '0.005*"ladrão" + 0.004*"jones" + 0.004*"bruxa" + 0.004*"força" + 0.004*"próprio" + 0.004*"banco" + 0.004*"enquanto" + 0.004*"coração" + 0.004*"tornar" + 0.003*"agora" + 0.003*"serviço" + 0.003*"lutar" + 0.003*"desconhecer" + 0.003*"tentar" + 0.003*"equipe" + 0.003*"destruir" + 0.003*"último" + 0.003*"inimigo" + 0.003*"sobre" + 0.003*"chamar"'),
 (1,
  '0.008*"guerra" + 0.005*"exército" + 0.005*"gangue" + 0.004*"filme" + 0.004*"durante" + 0.004*"mundial" + 0.004*"robert" + 0.004*"bandido" + 0.004*"oficial" + 0.004*"americano" + 0.003*"ano" + 0.003*"the" + 0.003*"dois" + 0.003*"romance" + 0.003*"campo" + 0.003*"mudança" + 0.003*"linha" + 0.003*"lucy" + 0.003*"quebrar" + 0.003*"chamar"'),
 (2,
  '0.008*"tornar" + 0.007*"enquanto" + 0.007*"vida" + 0.006*"novo" + 0.005*"ano" + 0.004*"encontrar" + 0.004*"história" + 0.004*"relacionamento" + 0.004*"dar" + 0.004*"york" + 0.003*"nova" + 0.003*"todo" + 0.003*"homem" + 0.003*"sobre" + 0.003*"poder" + 0.003*"dois" + 0.003*"velho" + 0.003*"enfrentar" + 0.003*"bom" + 0.003*"escapar"'),
 (3,
  '0.009*"ano" + 0.008*"vida" + 0.007*"todo" + 0.006*"poder" + 0.005*"jovem" + 0.005*"onde" + 0.005*"outro" + 0.005*"dois" + 0.004*"homem" + 0.004*"chegar" + 0.004*"conhecer" + 0.004*"mulher" + 0.004*"pai" + 0.004*"enquanto" + 0.004*"história" + 0.004*"mundo" + 0.003*"encontrar" + 0.003*"passar" + 0.003*"sobre" + 0.003*"casa"'),
 (4,
  '0.007*"descobrir" + 0.006*"encontrar" + 0.006*"jovem" + 0.006*"terra" + 0.005*"contra" + 0.005*"cidade" + 0.005*"missão" + 0.005*"dever" + 0.005*"homem" + 0.005*"grupo" + 0.005*"guerra" + 0.005*"matar" + 0.004*"enquanto" + 0.004*"poder" + 0.004*"grande" + 0.004*"começar" + 0.004*"tentar" + 0.004*"mundo" + 0.004*"morte" + 0.004*"durante"'),
 (5,
  '0.006*"ano" + 0.005*"fazer" + 0.005*"médio" + 0.005*"casa" + 0.004*"ensino" + 0.004*"tentar" + 0.004*"poder" + 0.004*"grupo" + 0.004*"jovem" + 0.004*"vida" + 0.004*"cidade" + 0.004*"grande" + 0.004*"após" + 0.003*"criança" + 0.003*"começar" + 0.003*"pai" + 0.003*"michael" + 0.003*"ver" + 0.003*"família" + 0.003*"mundo"'),
 (6,
  '0.006*"lutar" + 0.006*"descobrir" + 0.005*"vez" + 0.005*"jovem" + 0.005*"dois" + 0.005*"vida" + 0.004*"ano" + 0.004*"história" + 0.004*"morte" + 0.004*"encontrar" + 0.004*"seguir" + 0.004*"fazer" + 0.003*"após" + 0.003*"filme" + 0.003*"poder" + 0.003*"dever" + 0.003*"verdadeiro" + 0.003*"bom" + 0.003*"casa" + 0.003*"assassinato"'),
 (7,
  '0.008*"vida" + 0.006*"família" + 0.005*"ano" + 0.005*"dois" + 0.005*"pai" + 0.005*"jovem" + 0.005*"tornar" + 0.004*"história" + 0.004*"trabalho" + 0.004*"irmão" + 0.004*"levar" + 0.004*"novo" + 0.004*"unidos" + 0.003*"estados" + 0.003*"casa" + 0.003*"contra" + 0.003*"mãe" + 0.003*"mundo" + 0.003*"decidir" + 0.003*"criança"'),
 (8,
  '0.008*"vida" + 0.008*"filme" + 0.005*"ano" + 0.004*"enquanto" + 0.004*"fazer" + 0.004*"história" + 0.004*"sobre" + 0.004*"baixo" + 0.003*"levar" + 0.003*"seguir" + 0.003*"tornar" + 0.003*"george" + 0.003*"conhecer" + 0.003*"mudar" + 0.003*"tentar" + 0.003*"científico" + 0.003*"todo" + 0.002*"novo" + 0.002*"apaixonar" + 0.002*"tempo"'),
 (9,
  '0.010*"vida" + 0.010*"amigo" + 0.007*"descobrir" + 0.006*"novo" + 0.006*"família" + 0.005*"jovem" + 0.005*"pai" + 0.005*"fazer" + 0.005*"começar" + 0.004*"encontrar" + 0.004*"homem" + 0.004*"dever" + 0.004*"casa" + 0.004*"dois" + 0.004*"tudo" + 0.004*"ficar" + 0.004*"perder" + 0.004*"ano" + 0.004*"filho" + 0.004*"ter"')]

9 - Create a `for` loop to print each document and its distribution among topics. Use `lda_model.get_document_topics()`(Scores).

In [ ]:
# generate document-topic distributions
for i, doc in enumerate(corpus):
    doc_topics = lda_model.get_document_topics(doc)
    print(f"Document {i}: {doc_topics}")

Document 0: [(1, 0.2542863), (4, 0.6841163)]
Document 1: [(1, 0.3727837), (9, 0.59383684)]
Document 2: [(4, 0.8323124), (8, 0.14542103)]
Document 3: [(0, 0.11194908), (3, 0.41749018), (4, 0.42046648)]
Document 4: [(0, 0.13084902), (2, 0.33413678), (6, 0.14182718), (7, 0.36916292)]
Document 5: [(4, 0.067950524), (9, 0.89389926)]
Document 6: [(0, 0.09560691), (1, 0.028979938), (3, 0.5876315), (5, 0.11230724), (7, 0.16619892)]
Document 7: [(0, 0.14820151), (3, 0.70505464), (8, 0.10003187)]
Document 8: [(4, 0.15756814), (7, 0.8138252)]
Document 9: [(1, 0.3079705), (4, 0.28584442), (7, 0.35608253)]
Document 10: [(3, 0.30184272), (4, 0.6765081)]
Document 11: [(2, 0.56374234), (4, 0.39409056)]
Document 12: [(3, 0.20310168), (4, 0.32139966), (7, 0.2758296), (8, 0.17233744)]
Document 13: [(0, 0.3011899), (3, 0.37201503), (6, 0.30176213)]
Document 14: [(3, 0.031370737), (4, 0.28720987), (6, 0.42200932), (7, 0.24971616)]
Document 15: [(7, 0.96083146)]
Document 16: [(0, 0.16077344), (4, 0.12636837), (7, 0.174138), (9, 0.49575508)]
Document 17: [(6, 0.95904183)]
Document 18: [(4, 0.64383644), (8, 0.306029)]
Document 19: [(1, 0.15684856), (6, 0.7986888)]
Document 20: [(0, 0.4948328), (1, 0.010008637), (2, 0.010010289), (3, 0.0100096455), (4, 0.42508748), (5, 0.0100084), (6, 0.010012747), (7, 0.010009216), (8, 0.010009875), (9, 0.010010931)]
Document 21: [(1, 0.2307669), (2, 0.460842), (8, 0.27653134)]
Document 22: [(4, 0.13574743), (7, 0.11294645), (9, 0.6974054)]
Document 23: [(3, 0.4784092), (5, 0.25564533), (9, 0.25531405)]
Document 24: [(0, 0.014288433), (1, 0.014288451), (2, 0.014290453), (3, 0.014291986), (4, 0.8713926), (5, 0.014288174), (6, 0.014289227), (7, 0.014288509), (8, 0.0142899025), (9, 0.0142922625)]
Document 25: [(7, 0.85680836), (8, 0.1257796)]
Document 26: [(3, 0.65092134), (8, 0.30459884)]
Document 27: [(3, 0.42313448), (4, 0.5323452)]
Document 28: [(4, 0.26868692), (8, 0.2195604), (9, 0.47054547)]
Document 29: [(9, 0.9399838)]
Document 30: [(7, 0.5501543), (9, 0.4316317)]
Document 31: [(5, 0.61130404), (9, 0.36762086)]
Document 32: [(3, 0.051376004), (8, 0.34663403), (9, 0.58137935)]
Document 33: [(0, 0.011112951), (1, 0.0111135775), (2, 0.011115012), (3, 0.011115754), (4, 0.0111148935), (5, 0.011115066), (6, 0.011116237), (7, 0.011115317), (8, 0.3648955), (9, 0.5461857)]
Document 34: [(3, 0.34381813), (4, 0.38016757), (6, 0.25654075)]
Document 35: [(4, 0.43190593), (7, 0.5013189)]
Document 36: [(4, 0.68397045), (8, 0.24302079)]
Document 37: [(1, 0.68811136), (7, 0.28328776)]
Document 38: [(1, 0.49697804), (8, 0.124638915), (9, 0.35647774)]
Document 39: [(5, 0.41567925), (9, 0.53089064)]
Document 40: [(4, 0.682781), (9, 0.27718845)]
Document 41: [(0, 0.010013031), (1, 0.0100130215), (2, 0.010012567), (3, 0.010012345), (4, 0.68409556), (5, 0.010015553), (6, 0.010012462), (7, 0.0100130625), (8, 0.010011825), (9, 0.23580058)]
Document 42: [(3, 0.25591588), (7, 0.72120434)]
Document 43: [(4, 0.9549837)]
Document 44: [(3, 0.9181118)]
Document 45: [(8, 0.94701827)]
Document 46: [(1, 0.3761571), (4, 0.26652533), (5, 0.08916328), (9, 0.25233942)]
Document 47: [(2, 0.6834297), (4, 0.29432374)]
Document 48: [(4, 0.7731436), (8, 0.17347182)]
Document 49: [(8, 0.19771022), (9, 0.7406648)]
Document 50: [(6, 0.94367546)]
Document 51: [(3, 0.93568426)]
Document 52: [(9, 0.9709099)]
Document 53: [(4, 0.3818366), (9, 0.58331764)]
Document 54: [(4, 0.6732295), (6, 0.17226398), (9, 0.13697205)]
Document 55: [(1, 0.7217254), (5, 0.25538522)]
Document 56: [(7, 0.952602)]
Document 57: [(1, 0.33663163), (9, 0.5966386)]
Document 58: [(0, 0.050002933), (1, 0.050002933), (2, 0.050002933), (3, 0.5499622), (4, 0.050002933), (5, 0.05000425), (6, 0.05000582), (7, 0.050002933), (8, 0.050009303), (9, 0.050003704)]
Document 59: [(3, 0.48819986), (6, 0.48101693)]
Document 60: [(3, 0.52599293), (8, 0.42949948)]
Document 61: [(4, 0.5406609), (5, 0.40212235)]
Document 62: [(3, 0.9306705)]
Document 63: [(9, 0.93558776)]
Document 64: [(2, 0.4622006), (4, 0.1596231), (6, 0.16836558), (9, 0.19583608)]
Document 65: [(1, 0.2952951), (7, 0.6512785)]
Document 66: [(0, 0.11281985), (4, 0.5670412), (9, 0.26172778)]
Document 67: [(1, 0.06862492), (3, 0.21822421), (8, 0.6991316)]
Document 68: [(9, 0.93556833)]
Document 69: [(0, 0.38230234), (4, 0.44136715), (6, 0.1351155)]
Document 70: [(7, 0.9399817)]
Document 71: [(7, 0.06322372), (9, 0.9132225)]
Document 72: [(2, 0.96782863)]
Document 73: [(4, 0.27453223), (7, 0.4350926), (9, 0.27925032)]
Document 74: [(3, 0.70216936), (4, 0.12737638), (5, 0.15746903)]
Document 75: [(4, 0.28416163), (9, 0.67131203)]
Document 76: [(3, 0.38393262), (6, 0.36361897), (7, 0.20575435)]
Document 77: [(2, 0.97628534)]
Document 78: [(1, 0.45104298), (2, 0.12564819), (7, 0.16176215), (9, 0.24876308)]
Document 79: [(8, 0.9653476)]
Document 80: [(0, 0.6522394), (4, 0.3227387)]
Document 81: [(2, 0.49242195), (9, 0.48649746)]
Document 82: [(2, 0.6300498), (9, 0.33915025)]
Document 83: [(1, 0.1904646), (7, 0.5840224), (9, 0.18861379)]
Document 84: [(4, 0.738745), (9, 0.24217507)]
Document 85: [(4, 0.8074474), (5, 0.07263186), (8, 0.10500042)]
Document 86: [(0, 0.01432223), (1, 0.014323308), (2, 0.014325193), (3, 0.01432471), (4, 0.7263772), (5, 0.014329236), (6, 0.014323534), (7, 0.014324518), (8, 0.15902396), (9, 0.014326102)]
Document 87: [(0, 0.36667606), (1, 0.03333929), (2, 0.3666031), (3, 0.033343107), (4, 0.033340625), (5, 0.03333929), (6, 0.03333929), (7, 0.03333929), (8, 0.03333929), (9, 0.033340663)]
Document 88: [(5, 0.4363279), (6, 0.50647396)]
Document 89: [(0, 0.011138953), (1, 0.011139001), (2, 0.011139547), (3, 0.011147369), (4, 0.899736), (5, 0.011140298), (6, 0.011139694), (7, 0.011140064), (8, 0.011139433), (9, 0.01113967)]
Document 90: [(2, 0.11638985), (4, 0.3612404), (7, 0.50527203)]
Document 91: [(3, 0.22440778), (6, 0.27363035), (7, 0.48527336)]
Document 92: [(3, 0.20593214), (9, 0.77500397)]
Document 93: [(4, 0.23244257), (5, 0.1266491), (6, 0.6040278)]
Document 94: [(4, 0.322919), (8, 0.64505726)]
Document 95: [(0, 0.011115564), (1, 0.011119629), (2, 0.011119105), (3, 0.011119427), (4, 0.59849054), (5, 0.011123301), (6, 0.011123561), (7, 0.31255165), (8, 0.011117558), (9, 0.011119647)]
Document 96: [(1, 0.16220693), (2, 0.07524883), (4, 0.24398041), (8, 0.13029838), (9, 0.37932152)]
Document 97: [(0, 0.012507297), (1, 0.012507105), (2, 0.012508171), (3, 0.012507575), (4, 0.8874226), (5, 0.012507713), (6, 0.012507667), (7, 0.012517326), (8, 0.012506955), (9, 0.012507593)]
Document 98: [(3, 0.6155407), (4, 0.35243967)]
Document 99: [(4, 0.29374123), (8, 0.6395547)]
Document 100: [(4, 0.65104717), (6, 0.07504081), (7, 0.26220897)]
Document 101: [(0, 0.011125501), (1, 0.011126298), (2, 0.0111275), (3, 0.011129274), (4, 0.0111286435), (5, 0.01112631), (6, 0.011126057), (7, 0.011125747), (8, 0.011129236), (9, 0.8998554)]
Document 102: [(2, 0.13162622), (4, 0.7388808), (8, 0.08824429)]
Document 103: [(3, 0.9181192)]
Document 104: [(0, 0.7186053), (8, 0.23132074)]
Document 105: [(4, 0.935634)]
Document 106: [(4, 0.15105769), (7, 0.79891264)]
Document 107: [(4, 0.13284475), (6, 0.21266259), (7, 0.27135718), (8, 0.3608716)]
Document 108: [(0, 0.61378336), (8, 0.36842245)]
Document 109: [(2, 0.17996617), (9, 0.80049986)]
Document 110: [(3, 0.4804627), (4, 0.46236983)]
Document 111: [(0, 0.4652151), (1, 0.23384568), (3, 0.26908925)]
Document 112: [(8, 0.5977447), (9, 0.34885275)]
Document 113: [(6, 0.22332962), (8, 0.7458768)]
Document 114: [(3, 0.14617382), (9, 0.82519096)]
Document 115: [(2, 0.1314446), (9, 0.84800935)]
Document 116: [(0, 0.012529831), (1, 0.012513203), (2, 0.012514409), (3, 0.012515368), (4, 0.012516799), (5, 0.012515895), (6, 0.012513856), (7, 0.012513811), (8, 0.012514077), (9, 0.88735276)]
Document 117: [(0, 0.0125240125), (1, 0.0125251515), (2, 0.012524613), (3, 0.012527293), (4, 0.012525056), (5, 0.012524517), (6, 0.012525044), (7, 0.012526195), (8, 0.0125247715), (9, 0.8872733)]
Document 118: [(0, 0.45634332), (9, 0.49913782)]
Document 119: [(4, 0.93989617)]
Document 120: [(0, 0.0100114215), (1, 0.010010625), (2, 0.010013066), (3, 0.9098891), (4, 0.010016283), (5, 0.010011225), (6, 0.0100118965), (7, 0.010011265), (8, 0.010011749), (9, 0.010013355)]
Document 121: [(5, 0.30719787), (7, 0.4426398), (9, 0.19626077)]
Document 122: [(1, 0.4098282), (3, 0.28126642), (9, 0.2876733)]
Document 123: [(2, 0.9526128)]
Document 124: [(4, 0.9248615)]
Document 125: [(5, 0.7353378), (7, 0.22019146)]
Document 126: [(0, 0.010022528), (1, 0.010021812), (2, 0.010021812), (3, 0.010021826), (4, 0.90980154), (5, 0.01002199), (6, 0.010022566), (7, 0.010022052), (8, 0.010021812), (9, 0.010022051)]
Document 127: [(4, 0.89955825), (6, 0.067078285)]
Document 128: [(6, 0.93569714)]
Document 129: [(8, 0.9624692)]
Document 130: [(7, 0.9699667)]
Document 131: [(4, 0.9589694)]
Document 132: [(4, 0.42476454), (7, 0.5552105)]
Document 133: [(3, 0.7554138), (4, 0.19746095)]
Document 134: [(3, 0.76236933), (4, 0.20557976)]
Document 135: [(1, 0.33628944), (4, 0.17778419), (9, 0.46883354)]
Document 136: [(4, 0.609702), (5, 0.36526835)]
Document 137: [(6, 0.41346055), (9, 0.5517193)]
Document 138: [(4, 0.9525786)]
Document 139: [(7, 0.7214374), (9, 0.24215771)]
Document 140: [(0, 0.010014447), (1, 0.010012874), (2, 0.010012089), (3, 0.010012867), (4, 0.010013411), (5, 0.010013156), (6, 0.01001206), (7, 0.90988255), (8, 0.010012254), (9, 0.010014282)]
Document 141: [(6, 0.93073434)]
Document 142: [(4, 0.2061059), (5, 0.7405138)]
Document 143: [(9, 0.97091866)]
Document 144: [(3, 0.49519554), (8, 0.43808544)]
Document 145: [(9, 0.9437059)]
Document 146: [(4, 0.30168915), (9, 0.63151443)]
Document 147: [(6, 0.9470155)]
Document 148: [(8, 0.9499723)]
Document 149: [(3, 0.9356536)]
Document 150: [(2, 0.6159297), (7, 0.23301852), (9, 0.13731113)]
Document 151: [(0, 0.0100047635), (1, 0.010003014), (2, 0.010004257), (3, 0.0100045), (4, 0.010004596), (5, 0.010007221), (6, 0.2952732), (7, 0.010006799), (8, 0.62468714), (9, 0.01000451)]
Document 152: [(7, 0.65989375), (9, 0.3134029)]
Document 153: [(0, 0.2824107), (1, 0.012503073), (2, 0.012504929), (3, 0.012503859), (4, 0.012505798), (5, 0.6175478), (6, 0.012505261), (7, 0.012507738), (8, 0.012503999), (9, 0.012506814)]
Document 154: [(5, 0.947041)]
Document 155: [(2, 0.26283368), (5, 0.7155199)]
Document 156: [(1, 0.68088764), (5, 0.04844843), (9, 0.25397742)]
Document 157: [(4, 0.18991679), (5, 0.58771455), (6, 0.18116581)]
Document 158: [(3, 0.41365045), (4, 0.36672306), (9, 0.17293665)]
Document 159: [(4, 0.3785771), (7, 0.57137173)]
Document 160: [(4, 0.64675975), (7, 0.28648576)]
Document 161: [(4, 0.17338687), (9, 0.7692758)]
Document 162: [(4, 0.36601332), (9, 0.59757626)]
Document 163: [(2, 0.13266169), (4, 0.49510953), (5, 0.32547998)]
Document 164: [(9, 0.97426534)]
Document 165: [(2, 0.952588)]
Document 166: [(8, 0.96396774)]
Document 167: [(9, 0.9499632)]
Document 168: [(0, 0.016696103), (1, 0.01669976), (2, 0.016697265), (3, 0.016701676), (4, 0.69188607), (5, 0.17452611), (6, 0.016696524), (7, 0.016697157), (8, 0.016699625), (9, 0.016699675)]
Document 169: [(6, 0.93997145)]
Document 170: [(4, 0.21079421), (8, 0.75841546)]
Document 171: [(8, 0.9871302)]
Document 172: [(1, 0.40720698), (4, 0.23032583), (5, 0.14462209), (9, 0.1947365)]
Document 173: [(3, 0.41049948), (7, 0.43266216), (9, 0.10261606)]
Document 174: [(4, 0.1901171), (9, 0.7564594)]
Document 175: [(2, 0.58872694), (3, 0.35409543)]
Document 176: [(4, 0.36202142), (6, 0.58081245)]
Document 177: [(4, 0.2152955), (5, 0.3894133), (7, 0.34523836)]
Document 178: [(1, 0.21011175), (6, 0.11554398), (9, 0.6243168)]
Document 179: [(8, 0.9571072)]
Document 180: [(0, 0.010006503), (1, 0.010006092), (2, 0.010006933), (3, 0.010006215), (4, 0.01000678), (5, 0.909944), (6, 0.010005619), (7, 0.010005963), (8, 0.010005695), (9, 0.010006215)]
Document 181: [(0, 0.010014081), (1, 0.010012264), (2, 0.01001191), (3, 0.010011685), (4, 0.010014742), (5, 0.4851707), (6, 0.010013765), (7, 0.010013194), (8, 0.010010995), (9, 0.4347267)]
Document 182: [(8, 0.6148823), (9, 0.36347297)]
Document 183: [(6, 0.94997346)]
Document 184: [(0, 0.6661293), (6, 0.3096041)]
Document 185: [(2, 0.052242965), (4, 0.5528345), (5, 0.24293226), (9, 0.12793912)]
Document 186: [(6, 0.9499736)]
Document 187: [(2, 0.94996697)]
Document 188: [(0, 0.06638073), (3, 0.47835964), (9, 0.42605647)]
Document 189: [(6, 0.9249553)]
Document 190: [(0, 0.08063756), (9, 0.8659238)]
Document 191: [(3, 0.78905416), (5, 0.025169708), (6, 0.03047533), (9, 0.14605014)]
Document 192: [(0, 0.050002933), (1, 0.050002933), (2, 0.050002933), (3, 0.5499623), (4, 0.050002933), (5, 0.05000425), (6, 0.05000582), (7, 0.050002933), (8, 0.050009243), (9, 0.050003704)]
Document 193: [(2, 0.9749777)]
Document 194: [(5, 0.4077761), (9, 0.56867117)]
Document 195: [(4, 0.33674696), (9, 0.613225)]
Document 196: [(4, 0.22250237), (6, 0.31664476), (7, 0.16098836), (9, 0.28404674)]
Document 197: [(2, 0.3247333), (3, 0.63883007)]
Document 198: [(1, 0.51288575), (7, 0.46209404)]
Document 199: [(0, 0.5098779), (1, 0.010010266), (2, 0.010010703), (3, 0.010010936), (4, 0.010010248), (5, 0.0100092925), (6, 0.41003847), (7, 0.010011038), (8, 0.010009208), (9, 0.010011927)]
Document 200: [(3, 0.2962172), (7, 0.31062868), (8, 0.37563694)]
Document 201: [(4, 0.27247208), (7, 0.710475)]
Document 202: [(2, 0.6183294), (3, 0.1264429), (4, 0.17409956), (7, 0.064889774)]
Document 203: [(0, 0.01251106), (1, 0.012511164), (2, 0.012512722), (3, 0.012513469), (4, 0.8873865), (5, 0.012512136), (6, 0.0125120375), (7, 0.012514368), (8, 0.012512317), (9, 0.01251417)]
Document 204: [(3, 0.9624629)]
Document 205: [(3, 0.7801717), (8, 0.16641729)]
Document 206: [(0, 0.32926112), (3, 0.29795754), (4, 0.3447536)]
Document 207: [(6, 0.9399213)]
Document 208: [(6, 0.92495924)]
Document 209: [(5, 0.2575102), (6, 0.7024478)]
Document 210: [(6, 0.46023938), (9, 0.49973014)]
Document 211: [(9, 0.9768927)]
Document 212: [(0, 0.57159656), (5, 0.38130394)]
Document 213: [(8, 0.9356656)]
Document 214: [(3, 0.9639176)]
Document 215: [(1, 0.729638), (4, 0.2282286)]
Document 216: [(0, 0.050002933), (1, 0.050002933), (2, 0.050002933), (3, 0.5499623), (4, 0.050002933), (5, 0.05000425), (6, 0.05000582), (7, 0.050002933), (8, 0.050009236), (9, 0.050003704)]
Document 217: [(0, 0.18210141), (3, 0.55337554), (9, 0.24698098)]
Document 218: [(6, 0.4668922), (8, 0.26682788), (9, 0.25225887)]
Document 219: [(4, 0.9180844)]
Document 220: [(0, 0.08816773), (4, 0.44184795), (6, 0.43496656)]
Document 221: [(0, 0.014301667), (1, 0.014303103), (2, 0.0143016735), (3, 0.8712742), (4, 0.01430308), (5, 0.0143068945), (6, 0.0143019445), (7, 0.014300962), (8, 0.01430352), (9, 0.014303042)]
Document 222: [(2, 0.95495135)]
Document 223: [(7, 0.9904142)]
Document 224: [(3, 0.3485579), (6, 0.3307761), (8, 0.069589995), (9, 0.22099827)]
Document 225: [(1, 0.7906118), (2, 0.1807845)]
Document 226: [(3, 0.24770182), (9, 0.7021949)]
Document 227: [(6, 0.91812587)]
Document 228: [(6, 0.97270447)]
Document 229: [(6, 0.969968)]
Document 230: [(7, 0.71193933), (9, 0.27925986)]
Document 231: [(4, 0.3917123), (6, 0.5582154)]
Document 232: [(7, 0.23705931), (9, 0.7228593)]
Document 233: [(4, 0.74875784), (7, 0.22261372)]
Document 234: [(5, 0.067669116), (8, 0.049695216), (9, 0.8686127)]
Document 235: [(4, 0.9666399)]
Document 236: [(4, 0.24825774), (7, 0.7306658)]
Document 237: [(4, 0.5962351), (9, 0.3787377)]
Document 238: [(2, 0.6555578), (9, 0.29731986)]
Document 239: [(1, 0.092525415), (3, 0.5731481), (4, 0.29048562)]
Document 240: [(3, 0.95712507)]
Document 241: [(0, 0.50293785), (4, 0.1473721), (6, 0.16947646), (9, 0.168195)]
Document 242: [(3, 0.25499123), (4, 0.24869439), (9, 0.472148)]
Document 243: [(4, 0.22225465), (8, 0.74808085)]
Document 244: [(3, 0.8108724), (9, 0.15430894)]
Document 245: [(1, 0.26111507), (9, 0.68548703)]
Document 246: [(1, 0.5354235), (4, 0.42242727)]
Document 247: [(3, 0.35167897), (7, 0.10528099), (9, 0.50404495)]
Document 248: [(1, 0.41383955), (4, 0.53609437)]
Document 249: [(6, 0.9470146)]
Document 250: [(4, 0.96995443)]
Document 251: [(1, 0.09343686), (4, 0.14611842), (9, 0.71036303)]
Document 252: [(4, 0.8650287), (9, 0.09285277)]
Document 253: [(0, 0.011135457), (1, 0.011136148), (2, 0.011136288), (3, 0.42551035), (4, 0.4853981), (5, 0.011136119), (6, 0.011137224), (7, 0.011136077), (8, 0.01113557), (9, 0.011138717)]
Document 254: [(7, 0.9436955)]
Document 255: [(4, 0.42767036), (5, 0.53592825)]
Document 256: [(0, 0.012505721), (1, 0.012506169), (2, 0.012507078), (3, 0.22437051), (4, 0.012506581), (5, 0.012506788), (6, 0.012506237), (7, 0.012507587), (8, 0.012506994), (9, 0.6755763)]
Document 257: [(8, 0.9356443)]
Document 258: [(8, 0.97997904)]
Document 259: [(2, 0.94702584)]
Document 260: [(2, 0.9549622)]
Document 261: [(3, 0.50962794), (4, 0.13857137), (5, 0.09423146), (9, 0.25049657)]
Document 262: [(1, 0.46543947), (2, 0.5037701)]
Document 263: [(0, 0.5188427), (4, 0.18720777), (9, 0.26593035)]
Document 264: [(0, 0.11515954), (2, 0.5084141), (4, 0.32251805)]
Document 265: [(0, 0.48395765), (1, 0.01000364), (2, 0.010005428), (3, 0.010004885), (4, 0.010006188), (5, 0.010005122), (6, 0.01000534), (7, 0.010003746), (8, 0.010002796), (9, 0.4360052)]
Document 266: [(9, 0.96083313)]
Document 267: [(4, 0.9549392)]
Document 268: [(0, 0.24891543), (2, 0.121920735), (3, 0.060555495), (9, 0.5523708)]
Document 269: [(5, 0.11939082), (7, 0.81904227)]
Document 270: [(2, 0.118388735), (4, 0.36262894), (6, 0.13090025), (9, 0.34801865)]
Document 271: [(0, 0.1331483), (4, 0.40382016), (8, 0.4435649)]
Document 272: [(7, 0.97425956)]
Document 273: [(4, 0.395647), (7, 0.5662135)]
Document 274: [(9, 0.97092503)]
Document 275: [(0, 0.06380277), (4, 0.918782)]
Document 276: [(2, 0.37297544), (3, 0.46525812), (4, 0.1433255)]
Document 277: [(4, 0.4266938), (8, 0.5384872)]
Document 278: [(1, 0.5930613), (4, 0.39059553)]
Document 279: [(2, 0.94368887)]
Document 280: [(0, 0.056563567), (4, 0.9100722)]
Document 281: [(4, 0.3679721), (6, 0.58490384)]
Document 282: [(4, 0.21736181), (9, 0.7254642)]
Document 283: [(0, 0.56522405), (6, 0.4014021)]
Document 284: [(3, 0.96394026)]
Document 285: [(9, 0.94993955)]
Document 286: [(1, 0.976289)]
Document 287: [(2, 0.43243483), (9, 0.5204704)]
Document 288: [(7, 0.97854865)]
Document 289: [(3, 0.20405337), (4, 0.75142765)]
Document 290: [(9, 0.943686)]
Document 291: [(9, 0.976292)]
Document 292: [(6, 0.93560034)]
Document 293: [(0, 0.32135224), (5, 0.65700483)]
Document 294: [(9, 0.9470015)]
Document 295: [(4, 0.9526044)]
Document 296: [(2, 0.7521896), (9, 0.2287436)]
Document 297: [(9, 0.935694)]
Document 298: [(4, 0.24909937), (5, 0.7008575)]
Document 299: [(3, 0.095195204), (9, 0.8842523)]
Document 300: [(2, 0.6877629), (8, 0.2588524)]
Document 301: [(4, 0.38745055), (5, 0.40942168), (6, 0.1393225)]
Document 302: [(4, 0.28659442), (6, 0.68002856)]
Document 303: [(1, 0.9399617)]
Document 304: [(4, 0.39239645), (7, 0.53481835)]
Document 305: [(4, 0.9526004)]
Document 306: [(0, 0.120535515), (2, 0.4644747), (7, 0.35127616)]
Document 307: [(0, 0.071287155), (4, 0.5289145), (9, 0.373841)]
Document 308: [(4, 0.47777548), (7, 0.39410356), (9, 0.081399776)]
Document 309: [(2, 0.1887373), (4, 0.7854149)]
Document 310: [(9, 0.96533567)]
Document 311: [(5, 0.96894)]
Document 312: [(0, 0.010006026), (1, 0.010006918), (2, 0.90993786), (3, 0.0100072175), (4, 0.010007764), (5, 0.010006306), (6, 0.010006704), (7, 0.010007369), (8, 0.010006036), (9, 0.010007859)]
Document 313: [(7, 0.94698304)]
Document 314: [(3, 0.6540673), (4, 0.053302683), (9, 0.2823071)]
Document 315: [(6, 0.50147736), (9, 0.44843534)]
Document 316: [(1, 0.0741714), (3, 0.3758996), (4, 0.38621718), (5, 0.06581044), (6, 0.072869405)]
Document 317: [(0, 0.5921911), (4, 0.37300143)]
Document 318: [(9, 0.96662474)]
Document 319: [(3, 0.75883716), (7, 0.19900751)]
Document 320: [(4, 0.66257817), (5, 0.27585357)]
Document 321: [(7, 0.9590318)]

10 - Discuss the score in terms of what score would be sufficient to determine whether a document belongs to a topic or not.

11 - EXTRA

Study the pyLDAvis library to create direct graphs from the gensim library related to the model you just created.

In [ ]:
!pip install pyLDAvis

In [ ]:
# for LDA evaluation
import pyLDAvis
import pyLDAvis.gensim_models as gensimvisualize

pyLDAvis.enable_notebook(local=True)

In [ ]:
dickens_visual = gensimvisualize.prepare(lda_model, corpus, id2word, mds='mmds',sort_topics=False)
pyLDAvis.display(dickens_visual)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)